# 개발 환경 전용 설정 (거의 비워둬도 됨)
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

springdoc:
  cache:
    disabled: true                # 개발 단계에선 캐시 끄면 리로드 편함


