# 운영 환경에서만 필요한 설정만
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  main:
    banner-mode: off

# 보안 헤더 설정
server:
  # ALB 뒤에서 실행되므로 실제 클라이언트 IP를 얻기 위한 설정
  forward-headers-strategy: framework
  # HTTPS 리다이렉트 설정 (ALB에서 처리하므로 비활성화)
  ssl:
    enabled: false

# Actuator 설정 (프로덕션)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      cloudwatch:
        enabled: true
        namespace: HowAreYou/Backend