# 개발 환경 전용 설정 (거의 비워둬도 됨)
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    consumer:
      group-id: howru-dev
      auto-offset-reset: earliest
    # 로컬 개발 편의: 토픽 자동생성(브로커 옵션과 무관하게 AdminClient로 시도)
    admin:
      auto-create: true
      # 최신부트는 아래만으로 충분. 필요 시 spring.kafka.admin.auto-create=true 추가
      # auto-create는 스프링이 토픽을 만들도록 "시도"하는 옵션(존재 시 무시)
      # spring.kafka.admin.auto-create: true
    properties:
      # 디버깅 강화
      # "org.apache.kafka" 로그 레벨 INFO 이상으로 맞추면 콘솔에 잘 나옴
      # logging.level.org.apache.kafka=INFO
      # 개발에서만 요청 타임아웃 늘리고 재시도 줄이는 등 필요시 추가
      request.timeout.ms: 20000

springdoc:
  cache:
    disabled: true                # 개발 단계에선 캐시 끄면 리로드 편함


